name: Consistency

on:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  guard:
    uses: and3rn3t/.github/.github/workflows/reusable-consistency-guard.yml@main
    with:
      mode: warn
